<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Items', 'doctrine');

/**
 * BaseItems
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $item
 * @property Doctrine_Collection $Hours
 * 
 * @method integer             getId()    Returns the current record's "id" value
 * @method string              getItem()  Returns the current record's "item" value
 * @method Doctrine_Collection getHours() Returns the current record's "Hours" collection
 * @method Items               setId()    Sets the current record's "id" value
 * @method Items               setItem()  Sets the current record's "item" value
 * @method Items               setHours() Sets the current record's "Hours" collection
 * 
 * @package    myday
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseItems extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('items');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('item', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Hours', array(
             'local' => 'id',
             'foreign' => 'item_id'));
    }
}