<?php

/**
 * HoursTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HoursTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HoursTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Hours');
    }
}