<?php

/**
 * ItemsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ItemsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ItemsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Items');
    }
}